name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build Docker image
        run: docker build --tag itdogsoftware/aws-base:${{ github.sha }} .

  release:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and push Docker image
        run: |
          docker build --tag itdogsoftware/aws-base:${{ github.ref_name }} --tag itdogsoftware/aws-base:latest .
          docker push itdogsoftware/aws-base:${{ github.ref_name }}
          docker push itdogsoftware/aws-base:latest
